#!/bin/sh

####Feature annotation of states 
# written by Anna Malkowska 
# 26/04/2023

# Help                                                     #
############################################################
Help()
{
   # Display Help
   echo "Feature annotation of chromatin states. Uses bedmap to calculate the fraction of bases in a SORTED feature file (genes, TSS regions etc.) that have non-zero coverage from a chromatin state annotation file generated by ChromHMM. Creates a dataframe with the fraction of bases per state and reports the state with highest fraction in the annot column."
   echo
   echo "Syntax: feat_annot.sh"
   echo "options:"
   echo "h     Print this Help." 
   echo "s     Enter chromatin state file."
   echo "f     Enter feature bed file. NB NEEDS TO BE SORTED!"
   echo "o     Enter a prefix to be added to the csv file. Default=feat"
   echo
}


# Set variables
State=""
Feature=""
Prefix="feat"

############################################################
# Process the input options. Add options as needed.        #
############################################################
# Get the options
while getopts "hs:f:o:" option; do
   case $option in
      h) # display Help
         Help
         exit;;
      s) # Enter state file
	 State=$OPTARG;;
      f) # Enter feature file 
	 Feature=$OPTARG;;
      o) #Enter prefix to be added to the final dataframe
	 Prefix=$OPTARG;;
     \?) # Invalid option
         echo "Error: Invalid option"
         exit;;
   esac
done

echo "Generating state tables..."
### 
Rscript --vanilla ./split_annot.R $State 

echo "Mapping onto features..."

for file in state*; do sort -k1,1 -k2,2n $file > sorted_$file; done  

for file in sorted_*; 
do bedmap --echo --bases-uniq-f $Feature $file | cut -f2- -d'|' | paste $Feature - | tr '|' '\t' > annot_$file;
done 

rm state* 
rm sorted_* 

echo "Generating dataframe and thresholding..."

Rscript --vanilla ./make_df_thr.R 
rm annot_sorted_state* 

mv gene_annot.csv $Prefix.annot.csv
